// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUA-Bn5nsGt-riJAVAjydCpZq0eMVezH8',
    appId: '1:1096887312254:web:9c676d5e6ed5f67195dd2f',
    messagingSenderId: '1096887312254',
    projectId: 'mynotes-flutterp-8d561',
    authDomain: 'mynotes-flutterp-8d561.firebaseapp.com',
    storageBucket: 'mynotes-flutterp-8d561.appspot.com',
    measurementId: 'G-FVXYDY8WSZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8y3NVjH81bviWwlHZfb_R4LLmchRXBEM',
    appId: '1:1096887312254:android:0cb470904532432695dd2f',
    messagingSenderId: '1096887312254',
    projectId: 'mynotes-flutterp-8d561',
    storageBucket: 'mynotes-flutterp-8d561.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBun89dIWFSe9NTS4BXJakp-WnHEtLe6t8',
    appId: '1:1096887312254:ios:4de96c7fb8c0f14395dd2f',
    messagingSenderId: '1096887312254',
    projectId: 'mynotes-flutterp-8d561',
    storageBucket: 'mynotes-flutterp-8d561.appspot.com',
    iosBundleId: 'com.me.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBun89dIWFSe9NTS4BXJakp-WnHEtLe6t8',
    appId: '1:1096887312254:ios:4de96c7fb8c0f14395dd2f',
    messagingSenderId: '1096887312254',
    projectId: 'mynotes-flutterp-8d561',
    storageBucket: 'mynotes-flutterp-8d561.appspot.com',
    iosBundleId: 'com.me.mynotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUA-Bn5nsGt-riJAVAjydCpZq0eMVezH8',
    appId: '1:1096887312254:web:67d177b32bdade0895dd2f',
    messagingSenderId: '1096887312254',
    projectId: 'mynotes-flutterp-8d561',
    authDomain: 'mynotes-flutterp-8d561.firebaseapp.com',
    storageBucket: 'mynotes-flutterp-8d561.appspot.com',
    measurementId: 'G-EMZ33GGV0P',
  );
}
